'use client';
import { motion } from 'framer-motion';
import { CloudRain, Zap, QrCode } from 'lucide-react';

const features = [
  {
    icon: <CloudRain size={32} className="text-blue-400" />,
    title: 'Context Sensing',
    description: 'Weather, time, location, and merchant demand — read in real time to understand the moment.',
  },
  {
    icon: <Zap size={32} className="text-yellow-400" />,
    title: 'AI Offer Engine',
    description: 'Rules set by merchants. Offers generated by AI. Every deal is unique to this person, at this minute.',
  },
  {
    icon: <QrCode size={32} className="text-green-400" />,
    title: 'QR Redemption',
    description: 'One tap to claim. One scan to redeem. No app install, no loyalty card, no friction.',
  },
];

export default function FeatureCards() {
  return (
    <section style={{ backgroundColor: '#020617', padding: '6rem 1.5rem' }}>
      <div style={{ maxWidth: '64rem', margin: '0 auto', textAlign: 'center' }}>
        <h2 style={{ color: 'white', fontSize: '1.875rem', fontWeight: 'bold', marginBottom: '1rem' }}>How it works</h2>
        <p style={{ color: '#94a3b8', marginBottom: '3rem' }}>Three layers. One seamless experience.</p>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '1.5rem' }}>
          {features.map((feature, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: i * 0.1 }}
              whileHover={{ y: -4 }}
              style={{
                backgroundColor: '#0f172a',
                border: '1px solid #1e293b',
                borderRadius: '0.75rem',
                padding: '1.5rem',
                textAlign: 'left',
              }}
            >
              <div style={{ marginBottom: '1rem' }}>{feature.icon}</div>
              <h3 style={{ color: 'white', fontWeight: '600', fontSize: '1.125rem', marginBottom: '0.5rem' }}>{feature.title}</h3>
              <p style={{ color: '#94a3b8', fontSize: '0.875rem', lineHeight: '1.6' }}>{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}